spring:
  h2:
    console:
      enabled: true

  datasource:
    url:  jdbc:h2:mem:testdb

  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp


logging:
  level:
    org:
      springframework: info

server:
  error:
    include-message: always